# -*- coding: utf-8 -*-
"""NER_NO_INIT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Me-iS0rfYc6_XP4BikbflHhROp8jqXbF
"""

!apt-get update -qq 2>&1 > /dev/null
!apt-get install -y -qq software-properties-common python-software-properties module-init-tools
!add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
!apt-get update -qq 2>&1 > /dev/null
!apt-get -y install -qq google-drive-ocamlfuse fuse

from google.colab import drive
drive.mount('/content/drive')

cd /content/drive/My Drive/NLP/

!pip install pyvi

from NER3.data_utils import prepare_data
from NER3.ner_model import NERModel
from NER3.config import Config

# create instance of config
config = Config(pathfile='not_saved_sate_3/', name='savemodel_no_state')
# build model
model = NERModel(config)
model.build()

# create datasets
train_sents, train_labels, length_sentences = prepare_data(config.filename_train,config.vocab_words, config.vocab_chars, config.use_chars, colum=[0,3])
dev_sents, dev_labels, length_sentences_dev = prepare_data(config.filename_dev, config.vocab_words,config.vocab_chars, config.use_chars, colum=[0,3])
# train model
model.train(train_sents, train_labels, dev_sents,dev_labels)